-- AlterTable
ALTER TABLE "data_permohonan" ALTER COLUMN "tahun_pembuatan" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "isi_silinder" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "warna_kendaraan" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "bahan_bakar" SET DATA TYPE VARCHAR(25),
ALTER COLUMN "warna_tnkb" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "tahun_registrasi" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "kode_bank" SET DATA TYPE VARCHAR(20);
