-- CreateTable
CREATE TABLE "data_permohonan" (
    "id" SERIAL NOT NULL,
    "nama_pemohon" TEXT NOT NULL,
    "alamat_ktp" TEXT NOT NULL,
    "telepon" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "status_permohonan" INTEGER NOT NULL,
    "nomor_polisi" TEXT NOT NULL,
    "nama_pemilik" TEXT NOT NULL,
    "merek_kendaraan" TEXT NOT NULL,
    "alamat_stnk" TEXT NOT NULL,
    "jenis_kendaraan" TEXT NOT NULL,
    "model_kendaraan" TEXT NOT NULL,
    "tahun_pembuatan" TEXT NOT NULL,
    "isi_silinder" TEXT NOT NULL,
    "nomor_rangka" INTEGER NOT NULL,
    "nomor_mesin" INTEGER NOT NULL,
    "warna_kendaraan" TEXT NOT NULL,
    "bahan_bakar" TEXT NOT NULL,
    "warna_tnkb" TEXT NOT NULL,
    "tahun_registrasi" TEXT NOT NULL,
    "nomor_bpkb" TEXT NOT NULL,
    "masa_berlaku" TEXT NOT NULL,
    "jumlah_roda" INTEGER NOT NULL,
    "keterangan" TEXT,
    "foto_depan" TEXT NOT NULL,
    "foto_stnk" TEXT NOT NULL,
    "foto_ktp" TEXT NOT NULL,
    "foto_fc_kuning" TEXT NOT NULL,
    "foto_samping" TEXT NOT NULL,
    "foto_nib" TEXT NOT NULL,
    "provinsi" TEXT NOT NULL,
    "kota" TEXT NOT NULL,
    "penerbit" TEXT NOT NULL,

    CONSTRAINT "data_permohonan_pkey" PRIMARY KEY ("id")
);
